"""Initial Migration.

Revision ID: 9d7d0c3d065c
Revises: 
Create Date: 2023-11-18 14:19:10.921206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d7d0c3d065c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anime', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anime_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anime', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anime_name'))

    op.drop_table('anime')
    # ### end Alembic commands ###
